class ApiUrls {
  ApiUrls._();

  static const login = 'login';
  static const projectsCreate = 'projects/create';
  static const feeds = 'feeds';
  static const drives = 'drives';
  static const logs = 'logs';
  static const feedsDelete = 'feeds/delete';
  static const commentAdd = 'comment/add';
  static const drivesFolderAdd = 'drives/folder/add';
  static const projectsSalesProposals = 'projects/salesProposals';
  static const user = 'user';
  static const feedsSearch = 'feeds/search';
  static const commentFeedsMore = 'comment/feeds-more';
  static const feedsAdd = 'feeds/add';
  static const feedsEdit = 'feeds/edit';
  static const like = 'like';
  static const searchGlobally = 'search-globally';
  static const addPic = 'add_pic';
  static const users = 'users';
  static const weeklyHoursDelete = 'weeklyHours/delete';
  static const notificationsUpdateUncheck = 'notifications/update-uncheck';
  static const projects = 'projects';
  static const tasksAdd = 'tasks/add';
  static const tasksUpdate = 'tasks/update';
  static const commentUpdate = 'comment/update';
  static const commentDelete = 'comment/delete';
  static const weeklyHoursAdd = 'weeklyHours/add';
  static const weeklyHoursPause = 'weeklyHours/pause';
  static const commentList = 'comment/list';
  static const commentMore = 'comment/more';
  static const tasks = 'tasks';
  static const tasksView = 'tasks/view';
  static const notifications = 'notifications';
  static const leaves = 'leaves';
  static const dailyReport = 'daily-report';
  static const weeklyHours = 'weeklyHours';
  static const drivesAdd = 'drives/add';
}
