import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'team_portal': 'Team Portal',
          'welcome_back': 'Welcome back!',
          'sign_in_to_continue': 'Sign in to continue',
          'enter_email': 'Enter email',
          'email': 'Email',
          'password': 'Password',
          'sign_in': 'Sign In',
          'feeds': 'Feeds',
          'whats_on_your_mind': 'What’s on your mind?',
          'post': 'Post',
          'comments': 'Comments',
          'add_comment': 'Add comment...',
          'employees': 'Employees',
          'daily_report': 'Daily report',
          'projects': 'Projects',
          'tasks': 'Tasks',
          'logs': 'Logs',
          'leaves': 'Leaves',
          'log_out': 'Log out',
          'version': 'version',
          'search': 'Search',
          'profile': 'Profile',
          'contact_number': 'Contact number',
          'alternate_number': 'Alternate number',
          'date_of_birth': 'Date of birth',
          'current_address': 'Current address',
          'additional_info': 'Additional info',
          'edit_detail': 'Edit Detail',
          'edit_profile': 'Edit Profile',
          'edit_employee_info': 'Edit Employee Info',
          'save': 'Save',
          'enter_name': 'Enter name',
          'enter_contact_number': 'Enter contact no.',
          'enter_role': 'Enter role',
          'enter_position': 'Enter position',
          'enter_employee_id': 'Enter employee ID',
          'employee_id': 'Employee ID',
          'position': 'position',
          'role': 'Role',
          'enter_alternate_number': 'Enter alternate no.',
          'enter_date_of_birth': 'Enter date of birth',
          'enter_current_address': 'Enter current address',
          'enter_additional_info': 'Enter additional info',
          'take_a_photo': 'Take A Photo',
          'choose_from_gallery': 'Choose from library',
          'cancel': 'Cancel',
          'notification': 'Notification',
          'daily_reports': 'Daily Reports',
          'created': 'Created',
          'responsible': 'Responsible',
          'drives': 'Drives',
          'search_employees': 'Search employees',
          'information': 'Information',
          'document': 'Document',
          'position': 'Position',
          'employee_id': 'Employee ID',
          'registered_on': 'Registered On',
          'role': 'Role',
          'joining_date': 'Joining Date',
          'edit_information': 'Edit Information',
          'aadhar_card': 'Aadhar Card',
          'pan_card': 'Pan Card',
          'official_document': 'Official Document',
          'qualification_experience_document':
              'Qualification/Experience Document',
          'see_more': 'see more',
          'see_less': 'see less',
          'pending': 'Pending',
          'approved': 'Approved',
          'rejected': 'Rejected',
          'select_user': 'Select user',
          'value_time': 'Value time',
          'yesterday': 'Yesterday',
          'today': 'Today',
          'current_week': 'Current week',
          'current_month': 'Current month',
          'last_month': 'Last month',
          'total_hours': 'Total hours',
          'search_projects': 'Search projects',
          'create_a_project': 'Create a project',
          'task': 'Task',
          'drive': 'Drive',
          'edit': 'Edit',
          'access_detail': 'Access Detail',
          'add': 'Add',
          'ok': 'Ok',
          'no': 'No',
          'logout': 'Logout',
          'open': 'Open',
          'download': 'Download',
          'search_task': 'Search task',
          'add_new_task': 'Add new task',
          'create_new_project': 'Create new Project',
          'edit_project': 'Edit Project',
          'enter_project_name': 'Enter project name',
          'enter_task_name': 'Enter task name',
          'name': 'Name',
          'enter_client': 'Enter Client',
          'client': 'Client',
          'enter_url': 'Enter URL',
          'url': 'URL',
          'enter_portal': 'Enter portal',
          'portal': 'Portal',
          'enter': 'Enter',
          'enter_project_description': 'Enter project description',
          'enter_task_description': 'Enter task description',
          'description': 'Description',
          'create_project': 'Create Project',
          'high': 'High',
          'low': 'Low',
          'medium': 'Medium',
          'select_project': 'Select Project',
          'create_task': 'Create Task',
          'select_person': 'Select person',
          'person': 'Person',
          'priority': 'Priority',
          'select_priority': 'Select priority',
          'participants': 'Participants',
          'choose_participants': 'Choose participants',
          'observers': 'Observers',
          'choose_observers': 'Choose observers',
          'mm_dd_yy': 'mm/dd/yy',
          'start_date': 'Start Date',
          'end_date': 'End Date',
          'created_by': 'Created by',
          'responsible_person': 'Responsible person',
          'observer': 'Observer',
          'delete': 'Delete',
          'groups': 'Groups',
          'category': 'Category',
          'select_proposal': 'Select Proposal',
          'select_category': 'Select Category',
          'proposal': 'Proposal',
          'edit_task': 'Edit task',
          'create_folder': 'Create folder',
          'add_files': 'Add files',
          'enter_folder_name': 'Enter folder name',
          'create': 'Create',
          'folder': 'Folder',

          //
          'error': 'Error',
          'message_enter_email': 'Please enter your email address',
          'message_enter_folder_name': 'Please enter your folder name',
          'message_enter_role': 'Please enter role',
          'message_enter_position': 'Please enter position',
          'message_enter_employee_id': 'Please enter employee ID',
          'message_enter_password': 'Please enter your password',
          'message_server_error': 'Getting server error. Please try again!',
          'go_to_settings':
              'Please go to settings to allow permissions manually',
          'message_delete_post_take_confirmation':
              'Are you sure you want to delete this post',
          'open_settings': 'Open Settings',
          'message_login_again': 'Please login again to continue',
          'message_enter_name': 'Please enter your name',
          'message_enter_profile': 'Please enter profile',
          'message_enter_url': 'Please enter URL',
          'message_enter_portal': 'Please enter portal',
          'message_enter_valid_name': 'Please enter a valid name',
          'message_enter_valid_profile': 'Please enter valid profile',
          'message_enter_valid_url': 'Please enter a valid URL',
          'message_enter_valid_portal': 'Please enter a valid portal',
          'message_enter_contact_number': 'Please enter your contact number',
          'message_enter_alternate_number':
              'Please enter your alternate number',
          'message_enter_valid_contact_number':
              'Please enter a valid contact number',
          'message_enter_valid_alternate_number':
              'Please enter a valid alternate number',
          'message_enter_minimum_four_digits': 'Invalid No. Minimum 4 digits.',
          'message_enter_maximum_twelve_digits':
              'Invalid No. Maximum 12 digits.',
          'message_enter_current_address': 'Please enter current address',
          'message_enter_project_description':
              'Please enter project description',
          'message_enter_task_description': 'Please enter task description',
          'message_enter_project_name': 'Please enter project name',
          'message_enter_task_name': 'Please enter task name',
          'message_select_project': 'Please select project',
          'message_select_project_category': 'Please select project category',
          'message_select_proposal': 'Please select proposal',
          'message_select_person': 'Please select person',
          'message_select_priority': 'Please select priority',
          'message_select_participants': 'Please select participant(s)',
          'message_select_observers': 'Please select observer(s)',
          'message_enter_additional_info': 'Please enter additional info',
          'message_enter_date_of_birth': 'Please enter date of birth',
          'message_enter_start_date': 'Please enter start date',
          'message_enter_end_date': 'Please enter end date',
          'message_logout': 'Are you sure you want to log Out?',
        }
      };
}
